# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: x-cubed
  name: x-cubed
  namespace: default
  resourceVersion: "61439"
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: x-cubed
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: x-cubed
    spec:
      containers:
      - image: exkubed:latest
        imagePullPolicy: IfNotPresent
        name: exkubed
        ports:
          - containerPort: 4000
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}

# Loadbalancer Service
apiVersion: v1
kind: Service
metadata:
  name: x-cubed
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: x-cubed
  ports:
    - name: http
      port: 80
      targetPort: 4000
